name: Independent Jobs

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "inside job1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2
        run: | 
          az version
